version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: chatbot-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chatbot-backend
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: mongodb://root:example@mongodb:27017/admin
      PORT: 5000
      NLP_SERVICE_URL: http://nlp-service:5001
    depends_on:
      - mongodb
      - nlp-service
    restart: unless-stopped

  nlp-service:
    build:
      context: ./nlp
      dockerfile: Dockerfile
    container_name: chatbot-nlp
    ports:
      - "5001:5001"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chatbot-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongodb_data:
